### ISSUE TITLE
 Manual Install Instructions

### ISSUE THREAD

**Issue by italiangrandma** [mrgoodbytes8667/obsmessage#5]
Downloaded and realized there were no instructions for how to install:

Windows:

1) Unzip obsmessage-main.zip
2) Open File Explorer and navigate to %appdata%
3) Navigate to Roaming\Elgato\StreamDeck\Plugins
4) Drag and drop the "live.goodbytes.obsmessage.sdPlugin" folder there
5) Close and Reopen the Streamdeck software to see the plugin

**Comment by italiangrandma** [comment]
Well, I completely ignored the Releases section...These instructions are good if you want to manually install though!

**Comment by mrgoodbytes8667** [comment]
In all honesty, I'll still call that an oversight on my part. Having both sets of instructions both in the README and on each release would be wise.
