### ISSUE TITLE
OBS WebSocket v5 support

### ISSUE THREAD

**Issue by kaduwaengertner** [mrgoodbytes8667/obsmessage#8]
I`ve been using the OBS Message plugin for a long time and now that OBS 28 is released and using WebSocket v5 I`m wondering if the plugin its going to be update also to support this new version

**Comment by mrgoodbytes8667** [comment]
I'm working on this on #14. If you happen to have the latest Kruiz Control (as in, released an hour ago), and OBS v28 with websockets v5, and Stream Deck 5.3 (I know that's a lot), you're welcome to try the test build I'm attaching over on #14. My setup is a little outdated and I'm unsure if some of the issues right now are simply that I'm out of date.
